INSERT INTO teams (team_name) VALUES ('Arsenal') ON CONFLICT (team_name) DO NOTHING;
INSERT INTO teams (team_name) VALUES ('Aston Villa') ON CONFLICT (team_name) DO NOTHING;
INSERT INTO teams (team_name) VALUES ('Bournemouth') ON CONFLICT (team_name) DO NOTHING;
INSERT INTO teams (team_name) VALUES ('Brentford') ON CONFLICT (team_name) DO NOTHING;
INSERT INTO teams (team_name) VALUES ('Brighton') ON CONFLICT (team_name) DO NOTHING;
INSERT INTO teams (team_name) VALUES ('Burnley') ON CONFLICT (team_name) DO NOTHING;
INSERT INTO teams (team_name) VALUES ('Chelsea') ON CONFLICT (team_name) DO NOTHING;
INSERT INTO teams (team_name) VALUES ('Crystal Palace') ON CONFLICT (team_name) DO NOTHING;
INSERT INTO teams (team_name) VALUES ('Everton') ON CONFLICT (team_name) DO NOTHING;
INSERT INTO teams (team_name) VALUES ('Fulham') ON CONFLICT (team_name) DO NOTHING;
INSERT INTO teams (team_name) VALUES ('Ipswich') ON CONFLICT (team_name) DO NOTHING;
INSERT INTO teams (team_name) VALUES ('Leeds') ON CONFLICT (team_name) DO NOTHING;
INSERT INTO teams (team_name) VALUES ('Leicester') ON CONFLICT (team_name) DO NOTHING;
INSERT INTO teams (team_name) VALUES ('Liverpool') ON CONFLICT (team_name) DO NOTHING;
INSERT INTO teams (team_name) VALUES ('Luton') ON CONFLICT (team_name) DO NOTHING;
INSERT INTO teams (team_name) VALUES ('Manchester City') ON CONFLICT (team_name) DO NOTHING;
INSERT INTO teams (team_name) VALUES ('Manchester United') ON CONFLICT (team_name) DO NOTHING;
INSERT INTO teams (team_name) VALUES ('Newcastle') ON CONFLICT (team_name) DO NOTHING;
INSERT INTO teams (team_name) VALUES ('Nottingham Forest') ON CONFLICT (team_name) DO NOTHING;
INSERT INTO teams (team_name) VALUES ('Sheffield Utd') ON CONFLICT (team_name) DO NOTHING;
INSERT INTO teams (team_name) VALUES ('Southampton') ON CONFLICT (team_name) DO NOTHING;
INSERT INTO teams (team_name) VALUES ('Tottenham') ON CONFLICT (team_name) DO NOTHING;
INSERT INTO teams (team_name) VALUES ('West Ham') ON CONFLICT (team_name) DO NOTHING;
INSERT INTO teams (team_name) VALUES ('Wolves') ON CONFLICT (team_name) DO NOTHING;
